In [22]:
import numpy as np

In [23]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [24]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [29]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [30]:
a = np.array([[1,2,3],
              [4,5,6]])

In [31]:
a.shape

(2, 3)

In [32]:
a.ndim

2

In [33]:
a.size

6

In [34]:
a.dtype

dtype('int64')

In [35]:
a = np.array([10,20,30,40,50])

In [36]:
a[0]

np.int64(10)

In [37]:
a[-1]

np.int64(50)

In [38]:
a[1:3]

array([20, 30])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [42]:
np.random.rand(3,3)

array([[0.28093076, 0.00527337, 0.012804  ],
       [0.51842185, 0.91510241, 0.75380876],
       [0.35006966, 0.49479761, 0.55299073]])

In [50]:
np.random.rand(1,3)

array([[0.13303373, 0.11768655, 0.88647092]])

In [52]:
np.random.randint(1,100,(3,3))

array([[59, 97, 15],
       [86, 44, 86],
       [72, 22, 35]])

In [53]:
a = np.array([10,20,30])

a + 5

array([15, 25, 35])

In [55]:
import numpy as np

m = np.array([[10,20,30],
              [40,50,60]])

In [56]:
m[0,1]

np.int64(20)

In [57]:
m[1]

array([40, 50, 60])

In [58]:
m[:,2]

array([30, 60])

In [66]:
a = np.arange(12)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
m = np.array([[1,2,3],
              [4,5,6]])

In [76]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
m.flatten()

array([1, 2, 3, 4, 5, 6])

In [78]:
m.ravel()

array([1, 2, 3, 4, 5, 6])

In [79]:
a = np.array([10,25,3,47,8,33])

In [80]:
a > 20

array([False,  True, False,  True, False,  True])

In [81]:
a[a>20]

array([25, 47, 33])

In [90]:
a = np.array([[1],
              [2],
              [3]])

In [91]:
b = np.array([10,20,30])

In [92]:
c = a + b


In [85]:
a = np.array([1,2,3])

b = np.array([4,5,6])

In [86]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
a = np.array([0,1,2,3,4,5,6,7])

In [97]:
np.split(a,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [98]:
a = np.array([1,4,9,16])

np.sqrt(a)

array([1., 2., 3., 4.])

In [99]:
np.abs(a)

array([ 1,  4,  9, 16])

In [100]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

In [101]:
A * B

array([[ 5, 12],
       [21, 32]])

In [102]:
A @ B

array([[19, 22],
       [43, 50]])

In [110]:
np.random.seed(42)
np.random.randint(1, 10, 5)


array([7, 4, 8, 5, 7])

In [111]:
np.random.seed(42)
np.random.randint(1, 10, 5)


array([7, 4, 8, 5, 7])

In [112]:
import numpy as np

a = np.array([1,2,3])

b = a

In [113]:
b[0] = 99

In [115]:
a

array([99,  2,  3])

In [116]:
a = np.array([1,2,3])

c = a.copy()

In [117]:
c[0] = 99

In [118]:
a

array([1, 2, 3])